### ISSUE TITLE
Python 3 tornado add_done_callback problem

### ISSUE THREAD

**Issue by muhrin** [aiidateam/kiwipy#9]
In tornado>=5.0 on python 3 the event loop is now the asyncio one.  There is a point where we use `add_done_callback` to transform `tornado` futures into `kiwipy` ones.  Unfortunately with the `RmqThreadCommunicator` it uses add_done_callback from a thread other than that of the loop.  This in turn calls asyncio's `loop.call_soon` which is not thread safe.  This causes a race condition and would cause the tests the fail.  It's not clear exactly where to fix this but it will take more investigation.

For now, on python 3 we (unfortunately) revert back to tornado 4.0 versions.

**Comment by unkcpz** [comment]
The problem may be due to the fact that the new event loop was not opened in the new unittest and the previous event loop was used.
Clearing `IOLoop` in `RmqThreadCommunicator::stop` which make sure create new ioloop in each new test case can temporarily fix this bug. 
All unittest was passed when update to tornado>5
